---
title: "US Average Tuition Dashboard"
author: "Eric Helfrich, Derek Stanton, Karan Edikala"
output: flexdashboard::flex_dashboard
---

```{r setup}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(lubridate)
library(RColorBrewer)
library(usmap)
library(gganimate)
```

Column 1
-------------------------------------
    
### Chart 1
    
```{r, fig.height=10, fig.width=10}
# The graph and this code chunk are based off of the work by Paula Andrea Martinez's (@orchid00) Tidy Tuesday submission
# https://orchid00.github.io/us_avg_tuition.html

# The original graph modified
raw <- readxl::read_excel("./data/us_avg_tuition.xlsx")
# tidy dataset
mydata <- gather(raw, key = Year, value = Tuition, -State)

# clean years to have for digit numbers
mydata <- 
    mydata %>% 
    mutate(Year = str_sub(Year, start = 1, end = 4))

mydata1 <-
    mydata %>% 
    select(State, Tuition) %>% 
    group_by(State) %>% 
    summarise(Mean_State = mean(Tuition)) %>% 
    arrange(desc(Mean_State))

# With Respect to the mean

mydata2 <-
    mydata %>% 
    group_by(State) %>% 
    mutate(Mean_State = mean(Tuition)) %>% 
    ungroup() %>% 
    mutate(AwayFromMean = Mean_State - mean(Mean_State)) %>% 
    mutate(Category = ifelse(AwayFromMean < 0, "less than the mean", "higher than the mean")) %>% 
    arrange(desc(AwayFromMean)) %>% 
    select(State, AwayFromMean, Category) %>% 
    distinct()

# Theme provided by Paula Andrea Martinez @orchid00
theme_LPD <- function(){
  theme_bw() +
    theme(axis.text.x = element_text(size = 10, vjust = 1, hjust = 1), # Reduce text size
          axis.text.y = element_text(size = 10),
          axis.title.x = element_text(size = 14, face = "plain"),             
          axis.title.y = element_text(size = 14, face = "plain"),             
          panel.grid.major.x = element_blank(),                                          
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank(),  
          plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
          plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
          legend.position = "none"
    )
}


ggplot(mydata2) +
    geom_bar(aes(x = reorder(State, -AwayFromMean), y = AwayFromMean, 
                 fill = AwayFromMean),
             stat = "identity", position = "dodge") +
    geom_hline(yintercept = 0, linetype = 2) +
    ylim(-6000, 6000) + # set ylimit so both sides of the graph are even
    coord_flip() +
    scale_fill_distiller(type="div", palette="PiYG") +
    labs(x = "State", y = "Difference in Tuition Compared to US Average (Dollars)") +
    theme_LPD()
    
```

   
Column 2
-------------------------------------
   
### Chart 2

```{r}
# Input DF
df = read_excel("data/us_avg_tuition.xlsx")
# Tidying data
tidydf = gather(df, key = Year, value = Tuition, -State)
# Getting Just the year according to post
tidydf = tidydf %>% 
  mutate(Year = str_sub(Year, start = 1, end = 4))
# Calculating mean tuition fo state
tidydf = tidydf %>% 
  select(State, Tuition) %>% 
  group_by(State) %>% 
  summarise(Mean_State = mean(Tuition)) %>% 
  arrange(desc(Mean_State)) %>%
  mutate(fips = fips(State))

# Plot with usmap since we have a column named state
plot_usmap(data = tidydf, values = "Mean_State") + 
  scale_fill_distiller(palette = "Reds", direction = 1, name = "Tuition in Dollars" ) +
  labs(title = "Average Tuition by State") +
  theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
          plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
          legend.position = "right")

# Plotly
# g = list(scope = 'usa', projection = list(type = 'albers usa'))
# p = plot_geo(tidydf, locationmode = 'USA-states') %>%
#  add_trace( z = ~Mean_State, locations = ~State, color = ~Mean_State, colors = 'Reds') %>%
#  layout(geo = g)
```   
 
### Chart 3
    
```{r}
# Input DF
df = read_excel("data/us_avg_tuition.xlsx")
# Tidying data
tidydf = gather(df, key = Year, value = Tuition, -State)
# Getting Just the year according to post
st.reg <- data.frame(State = state.name, Region = state.region)
tidydf = tidydf %>% 
  mutate(Year = paste(Year, "-01", sep="")) %>%
  mutate(Year = year(ydm(Year, truncated = 2))) %>%
  left_join(st.reg, by="State") %>%
  group_by(Region, Year) %>%
  mutate(mean_region = mean(Tuition))
#gganimate
p = ggplot(tidydf, aes(x=Year, y=mean_region, color=Region)) +
  geom_line() +
  geom_point() +
  labs(y="Tuition", title="Average Tuition by US Census Region") +
  theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
          plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
          legend.position = "right") +
  transition_reveal(Year)
animate(p
```