---
title: "Automated Ticketing Classification with Shiny"
date: "2019-12-09"
author: "Karan Edikala, Eric Helfrich, Derek Stranton"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r knitr_init, echo=FALSE, cache=FALSE, warning=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```
 
# **DSBA-5122 Final Project**

## **Introduction: Domain Problem & Data Characterization**

### **Domain Problem**

We explored typical customer ticket classification data in an effort to grasp customer word usage and ticket results. Our domain problem is one for a back-end user/customer service agent to quickly and efficiently identify the problem and resolve the ticket. 

### **Data Characterization**

Tickets are generated by an enduser of a product or service. Customer service agents typically have to assign tags and/or categories to each ticket based on the nature of the problem, and route the ticket to the appropriate party for resolution. 

For data about common words used in a customer ticket, we acquired a public use dataset, via github, of typical words used in a ticket, and typical classifications of the ticket. 

### **Potential Users** 

The application is designed for customer service agent in any kind of field who handles the routing of customer submitted tickets.

### **Application Information**

The application is hosted at xxxxx_github

## **Chapter 1: Operations and Data Type Abstraction**

### **Data Operations**

The dataset used for this application was a public use file available on Github. 

### **Data Type Abstraction**



## **Chapter 2: Visual Encoding & Interaction Design** 
### **Visual Encoding**

### **Interaction Design** 

## **Chapter 3: Algorithmic Design** 

### **Design**

### **Performance** 

**Examle

```
example

```

## **Chapter 4: Evaluation**

### **User Evaluation**

### **Who is the User?** 

### **Using the Application**


## **Chapter 5: Conclusions**

### **Future Work** 

### **What's Next**


## **Appendix**
Exploratory work nthat didnt' make it into the app. Highlight what we have tried. 